# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: af2de95182575f19141f92d5b4948eff5e3a512e197369c29ed4f19b12573b4d3c1afe2d173b2d257e160c1f5e04a43d57a2c6ee2cec334bd70a09ced6128afb

test:
  secret_key_base: e3aabf6352fb80dfac0d624ade5e3c6635176b6802e72a2fcd4d0649ba6a2a10ba98c299816e35308573fba8f5451c1f81f2e79a619e7b9fa4d422376d76bc65

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
